### ISSUE TITLE
ACP/ACP3X/ACP6x Audio Coprocessor support?

### ISSUE THREAD

**Issue by PIut02** [qhuyduong/AMDMicrophone#1]
The coprocessor model is ACP/ACP3X/ACP6x Audio Coprocessor on the AMD 4000 series notebook,although it can be loaded,but the mic level is always full and there is no sound

**Comment by qhuyduong** [comment]
@PIut02 please run `ioreg -l` in the terminal and send me the result. I will try to support it.

**Comment by PIut02** [comment]
This is the result.[Result.txt](https://github.com/qhuyduong/AMDMicrophone/files/11952884/Result.txt)

**Comment by qhuyduong** [comment]
This is Renoir. It should work. hmmm

**Comment by qhuyduong** [comment]
How did you test it?

**Comment by PIut02** [comment]
> How did you test it?

I try to use voice memo and switched the mic,but no sound was recorded

**Comment by qhuyduong** [comment]
Did you select the `AMD Digital Microphone` in the Sound settings before recording?

**Comment by qhuyduong** [comment]
Hmm maybe this laptop still use HDA for microphone.

**Comment by qhuyduong** [comment]
You can verify by trying VoodooHDA to see if it works.

**Comment by PIut02** [comment]
I tried VoodooHDA and it does drive the mic,so this project doesn't work with such a laptop right?

**Comment by qhuyduong** [comment]
Yes this project focuses on ACP based microphone only. I'll add some notes about this in README. Thanks for trying.

**Comment by qhuyduong** [comment]
@PIut02 I'm planning to fix the microphone issue for non-ACP microphone. 'Cause I don't have any device, are you willing to help test it?

**Comment by PIut02** [comment]
Of course, I'm glad that you are able to fix this issue.

**Comment by qhuyduong** [comment]
Please join this channel https://t.me/+lOPZV3WXEwRkY2Nl so that we can easily discuss.

**Comment by PIut02** [comment]
I have already joined this channel. What do you need me to do now?

**Comment by qhuyduong** [comment]
I sent a message in Telegram.

**Comment by PIut02** [comment]
I seem to be unable to speak in the channel, so I am providing feedback here instead. This is the output result: [H94M.csv](https://github.com/qhuyduong/AMDMicrophone/files/12444807/H94M.csv). However, it should be noted that the official repository of applealc does not have nodes for the model I am using, and I am unsure if this will have any impact. Below is a version that I forked and modified [Version](https://github.com/PIut02/AppleALC).
