### ISSUE TITLE
The microphone works but the pitch is very strange/ 麦克风音准异常

### ISSUE THREAD

**Issue by IM1903** [qhuyduong/AMDMicrophone#13]
After installed this kernel ext. Record on Xiaomi laptop Pro 2021 14" causes weird voice pitch

Screenshot of Settings:
<img width="912" alt="Microphone shown in sound settings" src="https://github.com/qhuyduong/AMDMicrophone/assets/48363226/6daf8230-8100-4b2c-8b87-63972cab7775">

Screenshot kextstat:
<img width="995" alt="kextstat result" src="https://github.com/qhuyduong/AMDMicrophone/assets/48363226/c2f5d18f-9a26-44e3-a509-0fb4965a6e1b">

Here's 2 record sample, compares recording on laptop's mic and external USB microphone : [GoogleDrive](https://drive.google.com/file/d/1MlsJ-mog5z42mZYo2QY1yZG5MYrBZ-tb/view?usp=drive_link)

**Comment by qhuyduong** [comment]
Sorry I don't use hackintosh anymore.
