### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by palladinoandrea** [qhuyduong/AMDMicrophone#14]
I'm trying to compile via xcode and it gives me an error, is it possible to have the kext directly?

**Comment by qhuyduong** [comment]
You can find the kext in Artifacts under Actions

**Comment by palladinoandrea** [comment]
I did... It's just that like before, it's seen but it doesn't work

**Comment by palladinoandrea** [comment]
I did... It's just that like before, it's seen but it doesn't work

**Comment by qhuyduong** [comment]
You can find it in the Release now.
