### ISSUE TITLE
It didn't appear in Security & Privacy

### ISSUE THREAD

**Issue by arctangentx** [qhuyduong/AMDMicrophone#3]
I followed the steps, but in Security & Privacy appeared nothing

**Comment by arctangentx** [comment]
I finally solved it with csrutil enable --without kext in recovery mode

**Comment by qhuyduong** [comment]
How did you copy the kext to `/Library/Extensions` in the first place?
Please note that you have to copy it using the command line `sudo cp ...`. Drag and drop using Finder would not work.

**Comment by qhuyduong** [comment]
> I finally solved it with csrutil enable --without kext in recovery mode

This is equivalent to step 1 in the instruction.

You have to install it in the right order.

**Comment by Laurc2004** [comment]
<img width="745" alt="image" src="https://github.com/qhuyduong/AMDMicrophone/assets/119660750/c46e93ec-e834-4b26-949b-0b47ce67196e">
I have disabled it, but the 'Security and Privacy' interface still does not pop up. I have done all the previous steps.

**Comment by qhuyduong** [comment]
Can you run this command and give me the result?
```
sudo kextload -b com.qhuyduong.AMDMicrophone
```

**Comment by Laurc2004** [comment]
It has been resolved. I deleted the corresponding driver under extensions and it worked again after doing it once more.
Thank you for your response.

**Comment by Laurc2004** [comment]
> Can you run this command and give me the result?
> ```
> sudo kextload -b com.qhuyduong.AMDMicrophone
> ```

It has been resolved. I deleted the corresponding driver under extensions and it worked again after doing it once more.
Thank you for your response.
