### ISSUE TITLE
 Ryzen 3 3250U - Raven Ridge Support

### ISSUE THREAD

**Issue by hoaug-tran** [qhuyduong/AMDMicrophone#5]
hello, thank you for a great project for the community.

i know kext and i tried on my machine Ryzen 3 3250u ( Raven Ridge ) because it has Microphone Array device (it uses ACP right?) working.

I installed kext as your instructions. However. My microphone is still not working. and i think this is because my CPU base is not supported yet? can you support Raven Ridge in your project. I know it can be difficult but good looking forward to it.

Thank you very much. hope you have a great day.

![image](https://github.com/qhuyduong/AMDMicrophone/assets/92006941/cef94cbd-9302-4cd9-9d6f-a4eda2a99a3c)

![image](https://github.com/qhuyduong/AMDMicrophone/assets/92006941/61ae4d86-b399-4047-b593-bb58be0a2e90)

**Comment by qhuyduong** [comment]
https://github.com/qhuyduong/AppleALC/actions/runs/5996177267

@hoaug-tran can you try this fix to see if it works for you?
