### ISSUE TITLE
Support for other microphones

### ISSUE THREAD

**Issue by leyrshroud** [qhuyduong/AMDMicrophone#7]
Is there any other microphone support planned besides ACP based microphones? CPU is supported, but microphone is not, which is the problem. ACP is clearly present, but it's probably not being used by the laptop (Lenovo).

![microphone](https://github.com/qhuyduong/AMDMicrophone/assets/117598487/004b9211-79b7-4270-94e6-d6c422c1cb95)

**Comment by weng1277** [comment]
I have the same kind of CPU as you, my CPU is R5-4600H. I found the ACP device in AIDA64, but the audio input and output seems to still be Realtek, so it still can't be driven under MacOS.

**Comment by qhuyduong** [comment]
I'm working on this. However I don't have any device. If anyone is willing to help, please ping me at https://t.me/qhuyduong92

**Comment by qhuyduong** [comment]
https://github.com/qhuyduong/AppleALC/actions/runs/5996177267

Here is a potential fix.
